### ISSUE TITLE
Back-Front type sharing

### ISSUE THREAD

**Issue by ecogest** [luweglarz/ft_transcendence#49]
It would be nice to **find a better way to share interfaces** and types between the front and the back. Because at the moment, they are copied or rewritten by hand, which is tedious and very error prone.

**Comment by luweglarz** [comment]
Maybe we can use import/export and create a class folder into our sources.

Example:
```
// my-class.ts
export class MyClass {
  constructor(a) {
    this.a = a;
  }
}


// my-front-end.tss
import MyClass from '/somewhere/my-class.js';
const c = new MyClass('test');


// my-backend.ts
import MyClass from '/somewhere/my-class.js';
const c = new MyClass('test');
```

sources:
- https://stackoverflow.com/questions/61506268/can-it-be-possible-to-make-classes-that-can-be-referenced-by-back-end-and-front
- This one can be interesting to read, https://stackoverflow.com/questions/43142410/frontend-backend-class-exchange

**Comment by ecogest** [comment]
I don't think this solution would work out since both our front and back have their own root, and I believe you can't import stuff from a folder outside the root directory (I'll try, I am not 100% sure about this).

About the second post, I agree that we shouldn't too much time trying to achieve this and that front and back have different classes (a back user is not a front user). But regarding communication between front and back we need tightly synchronised interfaced. In practice, for example, if you rename in the back something that would need the exact same renaming in the front, we would gain a lot in sharing a single common interface (otherwise if we can quickly access variables that used to be defined and that are not anymore). The more complex our program is, the more often those bugs might happen.
